site_name: Working Software
site_url: https://github.com/working-software/working-software-best-practices
site_description: Working Software philosophy is the next evolution of Agile Development
site_author: xavi-reloaded
repo_url: https://github.com/working-software/working-software-best-practices

pages:
  - Home: index.md
  - General Philosophy: general_philosophy.md
  - Recommendations to start Working Software: recommendations.md
  - Software Architecture: software_architecture.md
  - Test Driven Development: test_driven_development.md
  - Working Software Tools: working_software_tools.md
  - Solid Principles: solid_principles.md
  - Future improvements: future_improvements.md
  - Bibliography: bibliography.md
  - About:
    - Reviewers: about/reviewers.md
    - License: about/license.md
    - Contributing: about/contributing.md

theme: 'material'

extra_css:
  - 'stylesheets/extra.css'

site_favicon: 'images/favicon.ico'
site_logo: 'images/favicon.ico'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/working-software'
    - type: 'twitter'
      link: 'https://twitter.com/xavi_reloaded'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/apiumtech'

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
